### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by thelonecabbage** [jslater89/pendulum#1]
Is the battery required to be a flat top?

Why do the calculations on the pendulum?  Why not send the raw data back to the server?

**Comment by thelonecabbage** [comment]
BTW: very interested in this project.  very cool.

**Comment by jslater89** [comment]
For some reason I remembered reading on Amazon that the slot was for flat tops, but the contacts in the battery slot are sufficiently springy that I don't think flat top is a requirement. I don't have any button-top batteries to test with, though.

I'm doing the calculations on the device primarily with an eye toward supporting alternate endpoints—if people want to integrate it into pre-existing systems, it helps to have all the data already figured out.
